// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// Staging (github.io project page) serves under /mann-ptsa-site/, so the
// deploy workflow sets ASTRO_SITE/ASTRO_BASE. Once mannptsa.org is attached,
// remove those env vars from the workflow and the defaults below take over.
export default defineConfig({
  site: process.env.ASTRO_SITE ?? 'https://mannptsa.org',
  base: process.env.ASTRO_BASE ?? '/',
  vite: {
    plugins: [tailwindcss()],
  },
  // Old OurSchoolPages URLs (from the July 2026 crawl — see archive/) → new homes.
  // Program/StudentLife pages point home until /programs/ ships; repoint them then.
  redirects: {
    '/Home': '/',
    '/Page/PTSA/Mission': '/about/',
    '/Page/PTSA/BoardMembers': '/about/',
    '/Page/PTSA/IncomingBoardMembers': '/about/',
    '/Page/PTSA/BoardChairs': '/about/',
    '/Page/PTSA/advocacy': '/about/',
    '/Page/PTSA/Resources': '/about/',
    '/ContactUs': '/about/',
    '/Directory': '/directory/',
    '/Packet/Join': '/join/',
    '/Page/Membership/Membership': '/join/',
    '/Page/Membership/meetings': '/about/',
    '/Page/Membership/Documents': '/about/',
    '/Page/Membership/awards': '/about/',
    '/Page/Membership/CommunitySponsorships': '/give/',
    '/Packet/PTSADonationGuest': '/give/',
    '/Page/Fundraising/coltcorral': '/give/',
    '/Page/Fundraising/fundraising': '/give/',
    '/Page/Fundraising/fredmeyercommunityrewards': '/give/',
    '/Page/Volunteers/Volunteer': '/volunteer/',
    '/Page/Volunteers/SignUps': '/volunteer/',
    '/Packet/signup': '/volunteer/',
    '/Event': '/events/',
    '/Event/ViewElsewhere': '/events/',
    '/Page/Fundraising/Events': '/events/',
    '/Page/Fundraising/familyfunnight': '/events/',
    '/Page/Fundraising/artnight': '/events/',
    '/Page/Fundraising/dancenight': '/events/',
    '/Page/Fundraising/bookfair': '/events/',
    '/Page/Fundraising/movienight': '/events/',
    '/Page/Fundraising/bikederby': '/events/',
    '/Packet/ScienceFair': '/events/',
    '/Packet/MathClub': '/',
    '/Page/Activities/Enrichment': '/',
    '/Page/Activities/Band_Orchestra': '/',
    '/Page/Activities/Math': '/',
    '/Page/Activities/ScienceFair': '/',
    '/Page/Activities/Art': '/',
    '/Page/Activities/Reflections': '/',
    '/Page/Activities/artdocents': '/',
    '/Page/Activities/classroomleads': '/',
    '/Page/Activities/spellingbee': '/',
    '/Page/Activities/EnrichmentRooms': '/',
    '/Page/Activities/mathk3enrichment': '/',
    '/Page/StudentLife/yearbook': '/',
    '/Page/StudentLife/music': '/',
    '/Page/StudentLife/spiritwear': '/',
    '/Page/StudentLife/hospitality': '/',
    '/Page/StudentLife/stafffavorites': '/',
    '/Page/StudentLife/lostandfound': '/',
  },
});
